//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Information
    {
        public int Student_Id { get; set; }
        public string Name { get; set; }
        public string Father_s_Name { get; set; }
        public string Mother_s_Name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public int Gender_Id { get; set; }
        public string Address { get; set; }
        public string Personal_Contact { get; set; }
        public string Father_s_Contact { get; set; }
        public string Mother_s_Contact { get; set; }
        public int Class { get; set; }
        public int Roll { get; set; }
        public string Institution { get; set; }
        public string Section { get; set; }
        public Nullable<int> Subject_Id { get; set; }
        public System.DateTime Admission_Date { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Class_Info Class_Info { get; set; }
        public virtual Gender_Info Gender_Info { get; set; }
        public virtual Subject_Info Subject_Info { get; set; }
    }
}
