//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Info
    {
        public Subject_Info()
        {
            this.Student_Information = new HashSet<Student_Information>();
        }
    
        public int Subject_Id { get; set; }
        public string Subject_Name { get; set; }
    
        public virtual ICollection<Student_Information> Student_Information { get; set; }
    }
}
